Publish function exec pass and fail cloud events with log emit
synadia-io/nex pull request #119
Opened 2024-02-12 16:48 UTC by autodidaddict

2024-02-12 18:44 UTC, kthomas requested changes
`triggerHandler` should be an instance method on `MachineManager` and should probably be named `handleTrigger` to align with naming convention followed across other handlers.

2024-02-12 19:07 UTC, autodidaddict commented
> `triggerHandler` should be an instance method on `MachineManager` and should probably be named `handleTrigger` to align with naming convention followed across other handlers.

Ok i'll make it an instance method. I go back and forth on naming conventions for funcs that return functions... I'll see what I can come up with.

2024-02-14 16:56 UTC, kthomas commented
There is one inconsistency in naming still between `publishFunctionExecSucceeded ` and `publishFuncExecFailed`. Otherwise LGTM.

2024-02-14 17:25 UTC, kthomas approved these changes

2024-02-14 17:36 UTC, merged