extracts process management into separate interface
synadia-io/nex pull request #155
Opened 2024-03-29 13:07 UTC by autodidaddict

everything should continue to work as it did before. Now, however, the firecracker process pool is in its own struct that conforms to the `ProcessManager` interface.

Note that  the workload manager proxy will fail tests because that proxy relied on magical knowledge of struct internals to do its job. We should find a different way to test these things so that we're only testing against the public interface and not using what should be hidden knowledge.

2024-04-01 16:30 UTC, kthomas requested changes

2024-04-01 17:03 UTC, autodidaddict commented
There is a 1:1 relation between workloads and agents, regardless of sandbox.

On Mon, Apr 1, 2024, 12:30 PM kt ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In internal/agent-api/client.go
> <https://github.com/synadia-io/nex/pull/155#discussion_r1544766552>:
>
> >  func (a *AgentClient) Id() string {
>  	return a.agentId
>  }
>
>  func (a *AgentClient) Start(agentId string) error {
> +	a.log.Info("Agent client starting", slog.String("workloadId", agentId))
>
> This kind of naming is harmful to baby seals and other endangered species.
>
> A workload is not an agent, so a workload id should not be set as an agent
> id or referred to as one. Iterative, I know, and similar to feedback I
> provided on #154 <https://github.com/synadia-io/nex/pull/154>.
> ------------------------------
>
> In internal/agent-api/client.go
> <https://github.com/synadia-io/nex/pull/155#discussion_r1544768226>:
>
> > @@ -80,6 +91,31 @@ func (a *AgentClient) Start(agentId string) error {
>  	return nil
>  }
>
> +func (a *AgentClient) RunTrigger(ctx context.Context, tracer trace.Tracer, subject string, data []byte) (*nats.Msg, error) {
>
> I do like AgentClient 👍🏻
> ------------------------------
>
> In internal/agent-api/types.go
> <https://github.com/synadia-io/nex/pull/155#discussion_r1544769184>:
>
> > @@ -127,7 +127,7 @@ func (r *DeployRequest) Validate() bool {
>  		err = errors.Join(err, errors.New("at least one trigger subject is required for this workload type"))
>  	}
>
> -	return err == nil
> +	return err
>
> This is more idiomatic to return an error 👍🏻
> ------------------------------
>
> In internal/control-api/types.go
> <https://github.com/synadia-io/nex/pull/155#discussion_r1544770758>:
>
> > @@ -52,10 +52,11 @@ type InfoResponse struct {
>  }
>
>  type MachineSummary struct {
> -	Id       string          `json:"id"`
> -	Healthy  bool            `json:"healthy"`
> -	Uptime   string          `json:"uptime"`
> -	Workload WorkloadSummary `json:"workload,omitempty"`
> +	Id        string          `json:"id"`
> +	Healthy   bool            `json:"healthy"`
> +	Uptime    string          `json:"uptime"`
>
> Why is uptime a string?
> ------------------------------
>
> In internal/node/controlapi.go
> <https://github.com/synadia-io/nex/pull/155#discussion_r1544771407>:
>
> > @@ -107,41 +107,41 @@ func (api *ApiListener) handleStop(m *nats.Msg) {
>  		return
>  	}
>
> -	vm := api.mgr.LookupMachine(request.WorkloadId)
> -	if vm == nil {
> -		api.log.Error("Stop request: no such workload", slog.String("vmid", request.WorkloadId))
> +	deployRequest, _ := api.mgr.LookupWorkload(request.WorkloadId)
>
> 👍🏻
> ------------------------------
>
> In internal/node/nodeproxy.go
> <https://github.com/synadia-io/nex/pull/155#discussion_r1544774665>:
>
> > @@ -73,11 +73,14 @@ func (m *MachineManagerProxy) Telemetry() *Telemetry {
>  }
>
>  func (m *MachineManagerProxy) VMs() map[string]*runningFirecracker {
> -	return m.m.allVMs
>
> I think we should keep this as much as possible -- even if that means
> refactoring it for now to ensure tests are not deleted but can instead
> pass. The tests are all still valid even though the underlying
> implementation and shape of the structs has changed.
> ------------------------------
>
> In internal/node/process_mgr.go
> <https://github.com/synadia-io/nex/pull/155#discussion_r1544776115>:
>
> >  }
>
> +// A process subscriber is any struct that wishes too be notified when a process manager has
> +// finished starting a process
> +type ProcessSubscriber interface {
> +	// Indicates that the process is now ready, and can be "prepared" for deployment
> +	OnProcessReady(workloadId string)
>
> What exactly does it mean for a process to be "ready"?
> ------------------------------
>
> In internal/node/running_vm.go
> <https://github.com/synadia-io/nex/pull/155#discussion_r1544776615>:
>
> > @@ -39,10 +39,6 @@ type runningFirecracker struct {
>  	workloadStarted time.Time
>  }
>
> -func (vm *runningFirecracker) isEssential() bool {
>
> Did this go somewhere else? It should have.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/synadia-io/nex/pull/155#pullrequestreview-1969342675>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADI4TIN5RMR7Q5SK6VD6EIDY3GDTVAVCNFSM6AAAAABFONBEG2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNRZGM2DENRXGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-02 12:37 UTC, autodidaddict commented on internal/node/process_mgr.go
> +	OnProcessReady(workloadId string)
discussed out of band

2024-04-02 12:37 UTC, autodidaddict commented on internal/node/running_vm.go
> -func (vm *runningFirecracker) isEssential() bool {
looks like it might've been lost in translation

2024-04-02 12:38 UTC, autodidaddict commented on internal/control-api/types.go
> +	Uptime    string          `json:"uptime"`
because it's formatted in human-friendly text, e.g. "2 hours, 12 minutes"

2024-04-02 14:56 UTC, kthomas commented on internal/node/running_vm.go
> -func (vm *runningFirecracker) isEssential() bool {
I will get it added back as part of my effort to fix broken tests 👍🏻

2024-04-03 13:03 UTC, autodidaddict commented on internal/agent-api/client.go
> +	agentID           string
all references to this ID should be workloadId

2024-04-03 13:10 UTC, autodidaddict reviewed
please address the change requests (I can't request changes on my own PR)

2024-04-03 13:10 UTC, autodidaddict commented on internal/node/process_mgr.go
> +	// FIXME-- rename to ListRunning()?
I'd rather not. All processes returned by this function are required to be "running". If there's a process that isn't up yet, the process manager doesn't let anyone know about it.

2024-04-03 13:10 UTC, autodidaddict commented on internal/node/process_mgr.go
> +type AgentDelegate interface {
please put this name back. AgentDelegate doesn't actually describe what this is. It is *not* an agent delegate, it's a process manager delegate.

2024-04-03 13:10 UTC, autodidaddict commented on internal/node/process_mgr.go
> +type AgentInfo struct {
Process Info

2024-04-03 14:03 UTC, kthomas approved these changes

2024-04-03 14:33 UTC, autodidaddict commented
Waiting for the results of manual testing on this before merging.

2024-04-03 18:36 UTC, kthomas approved these changes

2024-04-03 18:36 UTC, autodidaddict commented on internal/agent-api/client.go
> +		a.log.Debug(fmt.Sprintf("drained subscription to subject %s associated with agent client %s", sub.Subject, a.agentID))
this can probably be removed or put in trace, but not a big deal

2024-04-03 18:37 UTC, merged