trace behind debug tag
synadia-io/nex pull request #321
Opened 2024-07-11 13:27 UTC by jordan-rash

2024-07-11 13:47 UTC, autodidaddict submitted a review, later dismissed

2024-07-11 15:25 UTC, autodidaddict approved these changes

2024-07-11 15:42 UTC, kthomas requested changes
Can we revisit this after we get things stable?

2024-07-11 15:54 UTC, jordan-rash commented
> Can we revisit this after we get things stable?

We can leave this sitting here for now, but I dont want to cut a release until its merged

2024-07-31 19:50 UTC, kthomas approved these changes

2024-07-31 19:51 UTC, merged